<<<<<<< Updated upstream
# Generated by Django 5.2.1 on 2025-06-25 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_obra_encarregado_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='hotel_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema.hotel', verbose_name='Hotel vinculado'),
        ),
        migrations.AddField(
            model_name='obra',
            name='restaurante_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema.restaurante', verbose_name='Restaurante vinculado'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='encarregado_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to=settings.AUTH_USER_MODEL, verbose_name='Encarregado Vinculado'),
        ),
    ]
=======
# Generated by Django 5.2.1 on 2025-06-25 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_obra_encarregado_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='hotel_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema.hotel', verbose_name='Hotel vinculado'),
        ),
        migrations.AddField(
            model_name='obra',
            name='restaurante_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema.restaurante', verbose_name='Restaurante vinculado'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='encarregado_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to=settings.AUTH_USER_MODEL, verbose_name='Encarregado Vinculado'),
        ),
    ]
>>>>>>> Stashed changes
