# Generated by Django 5.2.1 on 2025-05-26 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('encarregado', 'Encarregado de Obra')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='restaurante',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='restaurante',
            name='avaliacao_entre_0_e_5',
        ),
        migrations.RemoveIndex(
            model_name='colaborador',
            name='Sistema_col_funcao_e9dd04_idx',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='data_demissao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='telefone_emergencia',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto Vinculado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sistema.obra'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
