# Generated by Django 5.2.1 on 2025-06-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_remove_colaborador_sistema_col_ativo_1317ed_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='empresa',
            field=models.CharField(max_length=100, verbose_name='Empresa Responsável'),
        ),
    ]
